# Generated by Django 2.0 on 2018-01-14 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_user_skills', to='wantedly_webapp.Skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wantedly_webapp.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='UserSkillUpvotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_upvote_by_user', to=settings.AUTH_USER_MODEL)),
                ('upvote_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_upvote_for_user', to=settings.AUTH_USER_MODEL)),
                ('user_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wantedly_webapp.UserSkill')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_skills',
            field=models.ManyToManyField(through='wantedly_webapp.UserSkill', to='wantedly_webapp.Skill'),
        ),
    ]
