# Generated by Django 2.0 on 2018-01-20 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wantedly_webapp', '0002_auto_20180119_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_skills',
            new_name='all_user_skills',
        ),
        migrations.AlterField(
            model_name='userskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_user_skills', to='wantedly_webapp.UserProfile'),
        ),
    ]
