# Generated by Django 2.0 on 2018-01-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wantedly_webapp', '0003_auto_20180120_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='all_user_skills',
            new_name='user_skills',
        ),
    ]
