# Generated by Django 2.0 on 2018-01-23 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wantedly_webapp', '0005_auto_20180121_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_skills',
            field=models.ManyToManyField(through='wantedly_webapp.UserSkill', to='wantedly_webapp.Skill'),
        ),
        migrations.AlterField(
            model_name='userskillupvotes',
            name='user_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_upvote_for_user_skill', to='wantedly_webapp.UserSkill'),
        ),
    ]
