# Generated by Django 2.0 on 2018-01-26 16:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wantedly_webapp', '0007_auto_20180123_2346'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together={('user', 'skill_item')},
        ),
        migrations.AlterUniqueTogether(
            name='userskillupvotes',
            unique_together={('skill', 'upvote_by', 'upvote_for')},
        ),
    ]
