# Generated by Django 2.0 on 2018-01-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wantedly_webapp', '0008_auto_20180126_2144'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('skill_name',)},
        ),
    ]
